/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    products: Product;
    downloads: Download;
    media: Media;
    categories: Category;
    'case-studies': CaseStudy;
    faqs: Faq;
    videos: Video;
    distributors: Distributor;
    jobs: Job;
    certifications: Certification;
    awards: Award;
    partners: Partner;
    solutions: Solution;
    'warranty-plans': WarrantyPlan;
    'sustainability-reports': SustainabilityReport;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'downloads' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    downloads: DownloadsSelect<false> | DownloadsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    distributors: DistributorsSelect<false> | DistributorsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    awards: AwardsSelect<false> | AwardsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    'warranty-plans': WarrantyPlansSelect<false> | WarrantyPlansSelect<true>;
    'sustainability-reports': SustainabilityReportsSelect<false> | SustainabilityReportsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
    home: Home;
    about: About;
    careers: Career;
    support: Support;
    sustainability: Sustainability;
    contact: Contact;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    careers: CareersSelect<false> | CareersSelect<true>;
    support: SupportSelect<false> | SupportSelect<true>;
    sustainability: SustainabilitySelect<false> | SustainabilitySelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | StatsGridBlock
    | CardGridBlock
    | CtaBandBlock
    | ContentPageBlock
    | IconFeatureBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Images, videos, and documents. Organize with folders (Hero, Products, Icons, …).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Required for accessibility and SEO.
   */
  alt: string;
  mediaType?: ('image' | 'video' | 'document' | 'icon') | null;
  /**
   * Optional labels for filtering (e.g. hero, product, partner).
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  videoResolution?: ('1080p' | '4k') | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  prefix?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    '4k'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'downloads';
          value: number | Download;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: ('downloads' | 'media')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Datasheets, manuals, certificates, and other product documents.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads".
 */
export interface Download {
  id: number;
  title: string;
  file: number | Media;
  documentType: 'datasheet' | 'manual' | 'certificate' | 'warranty' | 'brochure' | 'software';
  relatedProduct?: (number | null) | Product;
  locale?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
}
/**
 * Inverter models shown on the public product catalogue. Publish to appear on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Website label (Excel col J), e.g. "5kW OG6-GR1P5K-S(21A)".
   */
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Product family / category. Create categories first under Catalogue → Categories.
   */
  category: number | Category;
  /**
   * Datasheet model series (e.g. OG6-GR1P(2-3)K01-NV-YD). Used to group models on category pages.
   */
  modelSeries?: string | null;
  /**
   * Primary market segment for filtering and solutions pages.
   */
  segment?: ('residential' | 'commercial' | 'utility' | 'storage') | null;
  /**
   * Short summary shown on the product detail page.
   */
  shortDescription?: string | null;
  /**
   * Show in the Featured Models table on /products.
   */
  featured?: boolean | null;
  /**
   * e.g. 5 kW or 3.8 – 11.4 kW
   */
  powerRange?: string | null;
  /**
   * e.g. 98.7%
   */
  efficiency?: string | null;
  /**
   * e.g. Single Phase / Three Phase
   */
  phases?: string | null;
  /**
   * e.g. 10 Years
   */
  warranty?: string | null;
  /**
   * Additional rows on the product detail specs table (weight, dimensions, MPPT, etc.).
   */
  keySpecs?:
    | {
        label: string;
        value: string;
        unit?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Main product image on the detail page.
   */
  heroImage?: (number | null) | Media;
  gallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Product datasheet PDF.
   */
  datasheetPdf?: (number | null) | Media;
  /**
   * User / installation manual PDF.
   */
  manualPdf?: (number | null) | Media;
  /**
   * Long-form product content (optional).
   */
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Product families (e.g. Residential Grid-Tied). Create these first, then assign products to them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Category / product-family name shown in nav and on /products.
   */
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Lower numbers appear first in the Products menu and catalogue grid.
   */
  sortOrder?: number | null;
  /**
   * Short description for category cards and mega-menu.
   */
  description?: string | null;
  /**
   * Optional longer intro copy for the category landing page (SEO).
   */
  categoryIntroBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsGridBlock".
 */
export interface StatsGridBlock {
  eyebrow?: string | null;
  title?: string | null;
  stats: {
    /**
     * Preferred: upload an SVG/PNG icon.
     */
    icon?: (number | null) | Media;
    /**
     * Fallback Lucide icon when no upload is set.
     */
    iconKey?:
      | (
          | 'award'
          | 'globe'
          | 'headphones'
          | 'leaf'
          | 'microscope'
          | 'shield'
          | 'phone'
          | 'mail'
          | 'mapPin'
          | 'download'
          | 'wrench'
          | 'users'
          | 'building'
          | 'zap'
          | 'checkCircle'
        )
      | null;
    value: string;
    label: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'statsGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock".
 */
export interface CardGridBlock {
  eyebrow?: string | null;
  title?: string | null;
  cards: {
    /**
     * Preferred: upload an SVG/PNG icon.
     */
    icon?: (number | null) | Media;
    /**
     * Fallback Lucide icon when no upload is set.
     */
    iconKey?:
      | (
          | 'award'
          | 'globe'
          | 'headphones'
          | 'leaf'
          | 'microscope'
          | 'shield'
          | 'phone'
          | 'mail'
          | 'mapPin'
          | 'download'
          | 'wrench'
          | 'users'
          | 'building'
          | 'zap'
          | 'checkCircle'
        )
      | null;
    title: string;
    body: string;
    href?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBandBlock".
 */
export interface CtaBandBlock {
  title: string;
  body?: string | null;
  primaryCta: {
    label: string;
    /**
     * Internal path (/about) or full URL (https://…).
     */
    href: string;
  };
  secondaryCta?: {
    label?: string | null;
    /**
     * Internal path (/about) or full URL (https://…).
     */
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentPageBlock".
 */
export interface ContentPageBlock {
  sections: {
    heading: string;
    body: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'contentPage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconFeatureBlock".
 */
export interface IconFeatureBlock {
  /**
   * Preferred: upload an SVG/PNG icon.
   */
  icon?: (number | null) | Media;
  /**
   * Fallback Lucide icon when no upload is set.
   */
  iconKey?:
    | (
        | 'award'
        | 'globe'
        | 'headphones'
        | 'leaf'
        | 'microscope'
        | 'shield'
        | 'phone'
        | 'mail'
        | 'mapPin'
        | 'download'
        | 'wrench'
        | 'users'
        | 'building'
        | 'zap'
        | 'checkCircle'
      )
    | null;
  title: string;
  body: string;
  href?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'iconFeature';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  segment: string;
  capacity?: string | null;
  /**
   * Display string of product names.
   */
  products?: string | null;
  relatedProducts?: (number | Product)[] | null;
  location?: string | null;
  image?: (number | null) | Media;
  summary: string;
  challenge?: string | null;
  solution?: string | null;
  results?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  year?: string | null;
  featured?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  group: string;
  question: string;
  answer: string;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title: string;
  category?: string | null;
  duration?: string | null;
  thumbnail?: (number | null) | Media;
  /**
   * YouTube/Vimeo embed or watch URL.
   */
  embedUrl?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distributors".
 */
export interface Distributor {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  type: 'Distributor' | 'Certified Installer' | 'Service Center';
  city: string;
  state?: string | null;
  country: string;
  region: string;
  email?: string | null;
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  location: string;
  department?: string | null;
  type?: ('Full-time' | 'Part-time' | 'Contract' | 'Internship') | null;
  description?: string | null;
  applyUrl?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  name: string;
  scope?: string | null;
  region?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards".
 */
export interface Award {
  id: number;
  year: string;
  title: string;
  org?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  /**
   * e.g. Technology Partners
   */
  group: string;
  logo?: (number | null) | Media;
  url?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description: string;
  benefits?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  /**
   * Used to recommend catalogue products.
   */
  segmentKeys?: ('residential' | 'commercial' | 'utility' | 'storage')[] | null;
  primaryCta: {
    label: string;
    /**
     * Internal path (/about) or full URL (https://…).
     */
    href: string;
  };
  secondaryCta?: {
    label?: string | null;
    /**
     * Internal path (/about) or full URL (https://…).
     */
    href?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warranty-plans".
 */
export interface WarrantyPlan {
  id: number;
  productLine: string;
  standard: string;
  extended?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sustainability-reports".
 */
export interface SustainabilityReport {
  id: number;
  title: string;
  year: string;
  file?: (number | null) | Media;
  /**
   * Optional link if file is hosted elsewhere.
   */
  externalUrl?: string | null;
  size?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'downloads';
        value: number | Download;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'distributors';
        value: number | Distributor;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'awards';
        value: number | Award;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'solutions';
        value: number | Solution;
      } | null)
    | ({
        relationTo: 'warranty-plans';
        value: number | WarrantyPlan;
      } | null)
    | ({
        relationTo: 'sustainability-reports';
        value: number | SustainabilityReport;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        statsGrid?: T | StatsGridBlockSelect<T>;
        cardGrid?: T | CardGridBlockSelect<T>;
        ctaBand?: T | CtaBandBlockSelect<T>;
        contentPage?: T | ContentPageBlockSelect<T>;
        iconFeature?: T | IconFeatureBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsGridBlock_select".
 */
export interface StatsGridBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  stats?:
    | T
    | {
        icon?: T;
        iconKey?: T;
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock_select".
 */
export interface CardGridBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  cards?:
    | T
    | {
        icon?: T;
        iconKey?: T;
        title?: T;
        body?: T;
        href?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBandBlock_select".
 */
export interface CtaBandBlockSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentPageBlock_select".
 */
export interface ContentPageBlockSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconFeatureBlock_select".
 */
export interface IconFeatureBlockSelect<T extends boolean = true> {
  icon?: T;
  iconKey?: T;
  title?: T;
  body?: T;
  href?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  category?: T;
  modelSeries?: T;
  segment?: T;
  shortDescription?: T;
  featured?: T;
  powerRange?: T;
  efficiency?: T;
  phases?: T;
  warranty?: T;
  keySpecs?:
    | T
    | {
        label?: T;
        value?: T;
        unit?: T;
        id?: T;
      };
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  datasheetPdf?: T;
  manualPdf?: T;
  fullDescription?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads_select".
 */
export interface DownloadsSelect<T extends boolean = true> {
  title?: T;
  file?: T;
  documentType?: T;
  relatedProduct?: T;
  locale?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  mediaType?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  videoResolution?: T;
  caption?: T;
  prefix?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        '4k'?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  sortOrder?: T;
  description?: T;
  categoryIntroBody?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  segment?: T;
  capacity?: T;
  products?: T;
  relatedProducts?: T;
  location?: T;
  image?: T;
  summary?: T;
  challenge?: T;
  solution?: T;
  results?:
    | T
    | {
        text?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  year?: T;
  featured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  group?: T;
  question?: T;
  answer?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  duration?: T;
  thumbnail?: T;
  embedUrl?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distributors_select".
 */
export interface DistributorsSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  type?: T;
  city?: T;
  state?: T;
  country?: T;
  region?: T;
  email?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  location?: T;
  department?: T;
  type?: T;
  description?: T;
  applyUrl?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  name?: T;
  scope?: T;
  region?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards_select".
 */
export interface AwardsSelect<T extends boolean = true> {
  year?: T;
  title?: T;
  org?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  group?: T;
  logo?: T;
  url?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  benefits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  image?: T;
  segmentKeys?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warranty-plans_select".
 */
export interface WarrantyPlansSelect<T extends boolean = true> {
  productLine?: T;
  standard?: T;
  extended?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sustainability-reports_select".
 */
export interface SustainabilityReportsSelect<T extends boolean = true> {
  title?: T;
  year?: T;
  file?: T;
  externalUrl?: T;
  size?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Utility bar, CTAs, and mega-menus for the public site header.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  hotlineLabel?: string | null;
  localeLabel?: string | null;
  searchLabel?: string | null;
  loginLabel?: string | null;
  loginHref?: string | null;
  whereToBuy: {
    label: string;
    /**
     * Internal path (/about) or full URL (https://…).
     */
    href: string;
    id?: string | null;
  };
  requestQuote: {
    label: string;
    /**
     * Internal path (/about) or full URL (https://…).
     */
    href: string;
    id?: string | null;
  };
  /**
   * Order of top-level mega menus. Products columns are filled from the catalogue at render time.
   */
  primaryNav?:
    | {
        key: 'products';
        label: string;
        columns?:
          | {
              title: string;
              href?: string | null;
              links?:
                | {
                    label: string;
                    /**
                     * Internal path (/about) or full URL (https://…).
                     */
                    href: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Brand, SEO, analytics, footer, and social links used across the public site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Used in the footer copyright and default SEO titles.
   */
  siteName?: string | null;
  /**
   * Logo for dark backgrounds (header on navy, etc.).
   */
  logoLight?: (number | null) | Media;
  /**
   * Logo for light backgrounds.
   */
  logoDark?: (number | null) | Media;
  /**
   * Shown in the header utility bar.
   */
  hotline?: string | null;
  /**
   * Optional override. Leave blank to use “© {year} {site name}. All rights reserved.”
   */
  copyrightText?: string | null;
  /**
   * Default document title for pages without their own title.
   */
  seoTitle?: string | null;
  /**
   * Use %s for the page title, e.g. “%s | Oriana Inverters”.
   */
  seoTitleTemplate?: string | null;
  seoDescription?: string | null;
  /**
   * Twitter/X handle including @.
   */
  twitterHandle?: string | null;
  /**
   * Default social share image when a page has no OG image.
   */
  ogImage?: (number | null) | Media;
  /**
   * GA4 measurement ID, e.g. G-XXXXXXXXXX. Leave blank to disable.
   */
  googleAnalyticsId?: string | null;
  /**
   * GTM container ID, e.g. GTM-XXXXXXX. Leave blank to disable.
   */
  googleTagManagerId?: string | null;
  /**
   * Leave empty to keep the current built-in footer columns.
   */
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              /**
               * Internal path (/about) or full URL (https://…).
               */
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Privacy, terms, sitemap, etc. Empty keeps the current legal row.
   */
  legalLinks?:
    | {
        label: string;
        /**
         * Internal path (/about) or full URL (https://…).
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'linkedin' | 'facebook' | 'youtube' | 'instagram';
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Homepage hero, strategies, stats, and section copy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  heroMode?: ('fallback' | 'slides') | null;
  fallbackHero?: {
    eyebrow?: string | null;
    headline?: string | null;
    subheadline?: string | null;
    primaryCta: {
      label: string;
      /**
       * Internal path (/about) or full URL (https://…).
       */
      href: string;
      id?: string | null;
    };
    secondaryCta?: {
      label?: string | null;
      /**
       * Internal path (/about) or full URL (https://…).
       */
      href?: string | null;
    };
  };
  heroSlides?:
    | {
        image: number | Media;
        linkType: 'product' | 'post' | 'custom';
        product?: (number | null) | Product;
        post?: (number | null) | Post;
        href?: string | null;
        headline?: string | null;
        ctaLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  strategiesSection?: {
    eyebrow?: string | null;
    title?: string | null;
    intro?: string | null;
    items?:
      | {
          idKey: string;
          label: string;
          title: string;
          description: string;
          href: string;
          /**
           * Optional card image; UI may use mascot by idKey.
           */
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  impactSection: {
    eyebrow?: string | null;
    title?: string | null;
    link: {
      label: string;
      /**
       * Internal path (/about) or full URL (https://…).
       */
      href: string;
      id?: string | null;
    };
    stats?:
      | {
          /**
           * Preferred: upload an SVG/PNG icon.
           */
          icon?: (number | null) | Media;
          /**
           * Fallback Lucide icon when no upload is set.
           */
          iconKey?:
            | (
                | 'award'
                | 'globe'
                | 'headphones'
                | 'leaf'
                | 'microscope'
                | 'shield'
                | 'phone'
                | 'mail'
                | 'mapPin'
                | 'download'
                | 'wrench'
                | 'users'
                | 'building'
                | 'zap'
                | 'checkCircle'
              )
            | null;
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  whySection?: {
    eyebrow?: string | null;
    title?: string | null;
    body?: string | null;
    items?:
      | {
          /**
           * Preferred: upload an SVG/PNG icon.
           */
          icon?: (number | null) | Media;
          /**
           * Fallback Lucide icon when no upload is set.
           */
          iconKey?:
            | (
                | 'award'
                | 'globe'
                | 'headphones'
                | 'leaf'
                | 'microscope'
                | 'shield'
                | 'phone'
                | 'mail'
                | 'mapPin'
                | 'download'
                | 'wrench'
                | 'users'
                | 'building'
                | 'zap'
                | 'checkCircle'
              )
            | null;
          title: string;
          copy: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  reachSection: {
    eyebrow?: string | null;
    title?: string | null;
    body?: string | null;
    regions?:
      | {
          name: string;
          focus: string;
          id?: string | null;
        }[]
      | null;
    cta: {
      label: string;
      /**
       * Internal path (/about) or full URL (https://…).
       */
      href: string;
      id?: string | null;
    };
  };
  caseStudiesSection: {
    eyebrow?: string | null;
    title?: string | null;
    link: {
      label: string;
      /**
       * Internal path (/about) or full URL (https://…).
       */
      href: string;
      id?: string | null;
    };
    /**
     * How many published case studies to show.
     */
    limit?: number | null;
  };
  newsSection: {
    eyebrow?: string | null;
    title?: string | null;
    mode?: ('live' | 'manual') | null;
    manualItems?:
      | {
          title: string;
          date?: string | null;
          href: string;
          type?: string | null;
          id?: string | null;
        }[]
      | null;
    postsLimit?: number | null;
    link: {
      label: string;
      /**
       * Internal path (/about) or full URL (https://…).
       */
      href: string;
      id?: string | null;
    };
  };
  supportStrip: {
    hotlineLabel?: string | null;
    hotlineNote?: string | null;
    downloads?:
      | {
          label: string;
          /**
           * Internal path (/about) or full URL (https://…).
           */
          href: string;
          id?: string | null;
        }[]
      | null;
    partnerCta: {
      title?: string | null;
      body?: string | null;
      label: string;
      /**
       * Internal path (/about) or full URL (https://…).
       */
      href: string;
    };
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Company about page content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  hero: {
    /**
     * Small label above the title.
     */
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    image?: (number | null) | Media;
  };
  storyTitle?: string | null;
  storyParagraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  values?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: number;
  hero: {
    /**
     * Small label above the title.
     */
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    image?: (number | null) | Media;
  };
  image?: (number | null) | Media;
  whyTitle?: string | null;
  whyBody?: string | null;
  openingsTitle?: string | null;
  applyHref?: string | null;
  applyLabel?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support".
 */
export interface Support {
  id: number;
  hero: {
    /**
     * Small label above the title.
     */
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    image?: (number | null) | Media;
  };
  channels?:
    | {
        /**
         * Preferred: upload an SVG/PNG icon.
         */
        icon?: (number | null) | Media;
        /**
         * Fallback Lucide icon when no upload is set.
         */
        iconKey?:
          | (
              | 'award'
              | 'globe'
              | 'headphones'
              | 'leaf'
              | 'microscope'
              | 'shield'
              | 'phone'
              | 'mail'
              | 'mapPin'
              | 'download'
              | 'wrench'
              | 'users'
              | 'building'
              | 'zap'
              | 'checkCircle'
            )
          | null;
        title: string;
        detail: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  selfServiceTitle?: string | null;
  selfServiceLinks?:
    | {
        label: string;
        /**
         * Internal path (/about) or full URL (https://…).
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  ticketCta: {
    title?: string | null;
    body?: string | null;
    label: string;
    /**
     * Internal path (/about) or full URL (https://…).
     */
    href: string;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sustainability".
 */
export interface Sustainability {
  id: number;
  hero: {
    /**
     * Small label above the title.
     */
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    image?: (number | null) | Media;
  };
  image?: (number | null) | Media;
  highlights?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  approachTitle?: string | null;
  approachBody?: string | null;
  links?:
    | {
        label: string;
        /**
         * Internal path (/about) or full URL (https://…).
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  strategyHero?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
  };
  strategySections?:
    | {
        heading: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  hero: {
    /**
     * Small label above the title.
     */
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    image?: (number | null) | Media;
  };
  cards?:
    | {
        /**
         * Preferred: upload an SVG/PNG icon.
         */
        icon?: (number | null) | Media;
        /**
         * Fallback Lucide icon when no upload is set.
         */
        iconKey?:
          | (
              | 'award'
              | 'globe'
              | 'headphones'
              | 'leaf'
              | 'microscope'
              | 'shield'
              | 'phone'
              | 'mail'
              | 'mapPin'
              | 'download'
              | 'wrench'
              | 'users'
              | 'building'
              | 'zap'
              | 'checkCircle'
            )
          | null;
        title: string;
        detail: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Payload Form Builder form used on the contact page.
   */
  form?: (number | null) | Form;
  successMessage?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  hotlineLabel?: T;
  localeLabel?: T;
  searchLabel?: T;
  loginLabel?: T;
  loginHref?: T;
  whereToBuy?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  requestQuote?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  primaryNav?:
    | T
    | {
        key?: T;
        label?: T;
        columns?:
          | T
          | {
              title?: T;
              href?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logoLight?: T;
  logoDark?: T;
  hotline?: T;
  copyrightText?: T;
  seoTitle?: T;
  seoTitleTemplate?: T;
  seoDescription?: T;
  twitterHandle?: T;
  ogImage?: T;
  googleAnalyticsId?: T;
  googleTagManagerId?: T;
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroMode?: T;
  fallbackHero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        subheadline?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  heroSlides?:
    | T
    | {
        image?: T;
        linkType?: T;
        product?: T;
        post?: T;
        href?: T;
        headline?: T;
        ctaLabel?: T;
        id?: T;
      };
  strategiesSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        intro?: T;
        items?:
          | T
          | {
              idKey?: T;
              label?: T;
              title?: T;
              description?: T;
              href?: T;
              image?: T;
              id?: T;
            };
      };
  impactSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        link?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        stats?:
          | T
          | {
              icon?: T;
              iconKey?: T;
              value?: T;
              label?: T;
              id?: T;
            };
      };
  whySection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
        items?:
          | T
          | {
              icon?: T;
              iconKey?: T;
              title?: T;
              copy?: T;
              href?: T;
              id?: T;
            };
      };
  reachSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
        regions?:
          | T
          | {
              name?: T;
              focus?: T;
              id?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  caseStudiesSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        link?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        limit?: T;
      };
  newsSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        mode?: T;
        manualItems?:
          | T
          | {
              title?: T;
              date?: T;
              href?: T;
              type?: T;
              id?: T;
            };
        postsLimit?: T;
        link?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  supportStrip?:
    | T
    | {
        hotlineLabel?: T;
        hotlineNote?: T;
        downloads?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        partnerCta?:
          | T
          | {
              title?: T;
              body?: T;
              label?: T;
              href?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        image?: T;
      };
  storyTitle?: T;
  storyParagraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  values?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        image?: T;
      };
  image?: T;
  whyTitle?: T;
  whyBody?: T;
  openingsTitle?: T;
  applyHref?: T;
  applyLabel?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support_select".
 */
export interface SupportSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        image?: T;
      };
  channels?:
    | T
    | {
        icon?: T;
        iconKey?: T;
        title?: T;
        detail?: T;
        note?: T;
        id?: T;
      };
  selfServiceTitle?: T;
  selfServiceLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  ticketCta?:
    | T
    | {
        title?: T;
        body?: T;
        label?: T;
        href?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sustainability_select".
 */
export interface SustainabilitySelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        image?: T;
      };
  image?: T;
  highlights?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  approachTitle?: T;
  approachBody?: T;
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  strategyHero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  strategySections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        image?: T;
      };
  cards?:
    | T
    | {
        icon?: T;
        iconKey?: T;
        title?: T;
        detail?: T;
        id?: T;
      };
  form?: T;
  successMessage?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}